databases:
  - name: etsy-inventory-db
    databaseName: etsy_inventory_prod
    user: etsy_prod_user

services:
  - type: web
    name: etsy-inventory-saas
    env: python
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.13
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: etsy-inventory-db
          property: connectionString
      - key: ETSY_CLIENT_ID
        sync: false
      - key: ETSY_CLIENT_SECRET
        sync: false
      - key: ETSY_REDIRECT_URI
        sync: false
